### PR TITLE
Fix bug about fetching quotes (the old API respond with status 500...)

### PR DESCRIPTION
**Pull request by raphaelracine**
I resolve a bug about an old API (to fetch quotes) which is responds 500 now...

I had to change URL, and adapt JSON mapping in Quote.java.

### CODE REVIEW

**Comment by raphaelracine** [comment]
PS : It is normal than check fail, because the students have to implements :P

**Comment by edri** [comment]
Great! Did you try your modifications with the solution in order to know if everything is still working and if there ain't any side effects?

**Comment by raphaelracine** [comment]
> Great! Did you try your modifications with the solution in order to know if everything is still working and if there ain't any side effects?

Hello, yes i have tested it with all tests green (with my solution but it is the same solution than the "solution repository")... If all tests are green, ApplicationTest.java works.

**Review by edri — APPROVED** [review]

**Review by arubinst — APPROVED** [review]
Ok pour moi ! ;-)

**Comment by edri** [comment]
I forced the generation of random tags, since the new-used API does not use enough tags.

**Pull request merged**
